apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kubernetes/base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: inventory
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/port
        value: 8081

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: inventory
    patch: |-
      - op: replace
        path: /metadata/annotations/opspilot.dev~1revision
        value: "cccccccccccccccccccccccccccccccccccccccc"
